### ISSUE TITLE
DoubleDouble doesn't work with 0.4

### ISSUE THREAD

**Issue by laurentbartholdi** [simonbyrne/DoubleDouble.jl#6]
Dear Simon:
Using Julia v0.4, I notice a few warning/error messages with your package; probably easy to fix, but I'm new to Julia...

Version 0.4.0-dev+5497 (2015-06-21 17:56 UTC)
julia> using DoubleDouble
Warning: New definition
    call(Type{DoubleDouble.Double{#T<:Union{Float64, Float32}}}, Any, Any)
is ambiguous with:
    call(Type{#T<:FloatingPoint}, Real, Base.Rounding.RoundingMode) at rounding.jl:68.
To fix, define
    call(Type{DoubleDouble.Double{#T<:Union{Float64, Float32}}}, Real, Base.Rounding.RoundingMode)
before the new definition.

julia> x = double(pi)
Error showing value of type DoubleDouble.Double{Float64}:
ERROR: no promotion exists for DoubleDouble.Double{Float64} and Int64
 in _show at grisu.jl:62
...

Basic functionality seems OK:
julia> x = double(pi);
julia> float64(x)
WARNING: float64(x) is deprecated, use Float64(x) instead.
...
julia> Float64(x)
3.141592653589793

**Comment by simonbyrne** [comment]
Thanks. I don't really have time to look at this at the moment, but if you'd be willing to put together a pull request, I would be happy to review it.

**Comment by dpsanders** [comment]
Fixed by #7.
